image: cloudfoundry/inigo-ci

env:
  - GOROOT=/usr/local/go
  - GINKGO_PARALLEL=true
  - SHORT_TIMEOUT=2s
  - LONG_TIMEOUT=10s

script:
  - ./src/github.com/cloudfoundry-incubator/inigo/scripts/dev-test-inner
